title: "🚀 React-app-application"
description: "Production-ready React app deployment using Docker, Jenkins, and AWS."

remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

show_downloads: false

# Author details
author:
  name: Pavithra

# Repository info
repository: amie2001/Capstone-Project

# Optional footer or intro
footer_text: >
  👉 To know more about this project, visit the 
  [GitHub repository](https://github.com/amie2001/Capstone-Project/blob/dev/README.md)

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Build excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
